version: '3'

networks:
  backend:
    labels:
      description: backend services network
  api:
    labels:
      description: network for sharing server's container

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 9801:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=license-manager
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    hostname: license-manager-postgres
    networks:
      - backend
    restart: always

  mail-server:
    image: mailhog/mailhog:v1.0.1
    container_name: mail-server
    ports:
      - 9802:1025
      - 9803:8025
    environment:
      - MH_HOSTNAME=mail.license-manager
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=mailhog/e-mails
    hostname: license-manager-mail-server
    networks:
      - backend
    restart: always

  backend:
    build: ./backend
    image: license-manager/backend:1.0.0
    container_name: backend
    ports:
      - 9800:9800
    environment:
      - KEYSTORE_NAME=license-manager
      - KEYSTORE_PASSWORD=password
      - KEYSTORE_ALIAS=license-manager
      - POSTGRES_DB_URL=postgres:5432
      - POSTGRES_DB_NAME=license-manager
      - POSTGRES_DB_USERNAME=user
      - POSTGRES_DB_PASSWORD=password
      - MAIL_SERVER_HOST=mail-server
      - MAIL_SERVER_PORT=1025
    depends_on:
      - postgres
      - mail-server
    hostname: license-manager-backend
    networks:
      - backend
      - api
    restart: always

  reverse_proxy:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    hostname: license-manager-reverse-proxy
    networks:
      - api
    restart: always
