version: "3"

networks:
  backend:
    labels:
      description: backend services network
 
services:

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 9801:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=license-manager
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    hostname: license-manager-postgres
    networks:
      - backend
    restart: on-failure

  mail-server:
    image: mailhog/mailhog:v1.0.1
    container_name: mail-server
    ports:
      - 9802:1025
      - 9803:8025
    environment: 
      - MH_HOSTNAME=mail.license-manager
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=mailhog/e-mails
    hostname: license-manager-mail-server
    networks:
      - backend
    restart: on-failure

  backend:
    build: ./backend
    image: license-manager/backend:0.0.1
    container_name: backend
    ports:
      - 9800:9800
    environment:
      - KEYSTORE_NAME=license-manager
      - KEYSTORE_PASSWORD=password
      - KEYSTORE_ALIAS=license-manager
      - POSTGRES_DB_URL=postgres:5432
      - POSTGRES_DB_NAME=license-manager
      - POSTGRES_DB_USERNAME=user
      - POSTGRES_DB_PASSWORD=password
      - MAIL_SERVER_HOST=mail-server
      - MAIL_SERVER_PORT=1025
    depends_on:
      - postgres
      - mail-server
    hostname: license-manager-backend
    networks:
      - backend
    restart: on-failure
    